name: sync-to-gitee

on:
  push:
    branches: [main, dev, gh-pages]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.repository == 'doocs/qcloud-im-server-sdk-java'
    steps:
      - name: Sync to gitee.com
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:doocs/qcloud-im-server-sdk-java.git
          destination-repo: git@gitee.com:Doocs/qcloud-im-server-sdk-java.git
      
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: yanglbme
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: doocs/qcloud-im-server-sdk-java
          branch: gh-pages
